services:
  vector-tile-renderer:
    image: ghcr.io/consbio/mbgl-renderer:latest
    restart: unless-stopped
    networks:
      - vtg
    expose:
      - "80"
  vector-tile-cache:
    image: memcached:latest
    command: ["memcached", "-m", "2048", "-p", "11211", "-u", "memcache"]
    restart: unless-stopped
    networks:
      - vtg
    expose:
      - "11211"
  vector-tile-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - vtg
    ports:
      - "${VTG_PORT:-8080}:8080"
    environment:
      - VTG_TOKEN
    depends_on:
      - vector-tile-renderer
      - vector-tile-cache
networks:
  vtg: